angular.module('homeModule',[])
.config(function($stateProvider,$urlRouterProvider){
	$stateProvider
		.state('home',{
			url:'/home',
			templateUrl:'components/home/home.html',
			controller:'homecontrol',
			css:'components/home/home.css'
		})
})
.controller('homecontrol',['$scope',function($scope){
	$scope.name="三大12312";
}])
