angular.module('videoModule',[])
.config(function($stateProvider,$urlRouterProvider){
	$stateProvider
		.state('video',{
			url:'/video',
			templateUrl:'components/video/video.html',
			controller:'videoControl',
			css:'components/video/video.css'
		});
})
.controller('videoControl',['$scope','$http',function($scope,$http){
	console.log('ss');
		$http.get('components/video/json/轮播.json').success(function(res){
			$scope.arr=res.msg.reclist_236;
		});
}]);
